
/* Exercise 1: Write a program that calculates the double of the given number, and prints the value of parameter used in method, result generated by the method, and value of variable that is passed to the method.

desired output:
Initial value = 17
Final value = 34
x = 17

Initial value = 42
Final value = 84
number = 42




===================
Exercise 2: Write a program that generates the following output. Program should have a method which has two parameters (first one is character type which indicates the character to be printed out, and second parameter is int type and indicates how many times a given character will be printed out).

====================
>                  < 
>>                << 
>>>              <<< 
>>>>            <<<< 
>>>>>          <<<<< 
>>>>>>        <<<<<<
>>>>>>>      <<<<<<< 
>>>>>>>>    <<<<<<<<
>>>>>>>>>  <<<<<<<<<
>>>>>>>>>><<<<<<<<<<



===================
Exercise 3: Write a java program that calculates the sum of integers from 1 to N, by using Gauss' formula (i.e., sum = (n+1)*n/2). Program should have a method which takes the larges number in the series as a parameter.

Gauss' formula to calculate the sum of the first n integers:

(n+1)*n/2

e.g., sum of integers from 1 to 100.  
1	100
2	99
3	98
...     ...
100	1

(1+100)*100, gives us the summation of two series, thus we need to divide it by 2.
100x101 = 10100 / 2 = 5050



===================
Exercise 4: Write a java program that calculates the length of hypotenuse for a right angle triangle. Program should use a methdod that has two double type parameters, and return the length of hypotenuse as a double. You can use Math class methods.


===================
Exercise 5 (not covered in the lab session): Write a program that prints out the following output. The program should have a method called verse, and should have three String parameters, called item, verb, and sound.

The wheels on the bus go round and round,
round and round,
round and round.
The wheels on the bus go round and round,
All through the town.


The wipers on the bus go swish, swish, swish,
swish, swish, swish,
swish, swish, swish.
The wipers on the bus go swish, swish, swish,
All through the town.

The horn on the bus goes beep, beep, beep,
beep, beep, beep,
beep, beep, beep.
The horn on the bus goes beep, beep, beep,
All through the town.

===================
Exercise 6: Write a program that can find the largest absolute value for the given set of values. You can use Math class functions. You may also use method overloading that allows to use the same name for methods that have different number of parameters.

i) 7, -2, -11
ii) -4, 5, 2
ii) 6, 18

*/

public class lab06 {
    
}
